from . import res_country_state
from . import einvoice_catalog_05
from . import einvoice_catalog_07
from . import einvoice_catalog_09
from . import einvoice_catalog_10
from . import einvoice_catalog_17
from . import einvoice_catalog_25
from . import einvoice_catalog_51
from . import einvoice_catalog_54
from . import einvoice_catalog_payment
from . import account_tax
from . import account_move
from . import main_parameter
from . import res_partner
from . import einvoice
from . import einvoice_line
from . import product_template
from . import einvoice_catalog_01
from . import res_currency
from . import dummy_model